### PR TITLE
Fix addresses bug to default to United States

### LINKED ISSUE #1266: Address field set defaults to "Outside of US"
## Where are you in the form?

**Section:**
Relationships --> Relatives
**Question:**
Provide your relative's current address,  Provide your relative's place of birth
**Field:**
Was this person born in the United States of America?, This address is
**Component (for example address block):**
Address block

## What did you see?
- [ ] Validation error
- [ ] Data not saving
- [ ] Language or content issue
- [X] Other (explain below)

Sign in to new/fresh form. Go to relatives section. Click Mother, Click No to "deceased?". Click Save. Logout, log back in. Go back to Mother entry. 

Address blocks for birth and current address default to "Outside US".

screen shot 2018-12-14 at 9 40 00 am

screen shot 2018-12-14 at 9 40 05 am

## What did you expect to see?

Default to "In US", which was displayed on the original form creation/sign-in.

## Is this error limited to just this field or others in the form?

- [ ] Only relevant to just this question
- [x] Cross-form issue
- [ ] I don't know

Probably cross-form, but I don't know.

## What operating system and browser/version are you using?

**Operating system**
- [ ] Windows
- [X] MacOS

**Browser**
- [X] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge
- [ ] Other

**Version:**

### PR DESCRIPTION
**Pull request by christopherhuii**
Fixes #1266 and #1365 

This PR fixes two issues because they are somewhat related.

When a country field is fresh and untouched, it is initialized as:
```
{
  value: null
}
```

When a country field is loaded from the database, it is filled out as a string: "Canada"

When a country field is updated in the input field, it fills out as an object:
```
{
  value: "Cana"
}
```

Because of each of these cases, this is why we created the `countryString` function. I needed to tweak it a little bit so it knows how to handle `null` values.

### CODE REVIEW

File: src/components/Form/Location/Address.jsx [hunk 1]
```diff
@@ -394,7 +404,7 @@ export default class Address extends ValidationElement {
               </div>
             </div>
           </Show>
-          <Show when={isInternational(this.props)}>
```
Comment (hursey013) [inline src/components/Form/Location/Address.jsx]: Looks like this is the only instance of `isInternational` so it can be removed from the imports.

**Comment by hursey013** [comment]
Also out of curiosity, which aspect of this resolved #1365?

File: src/components/Form/Location/Address.jsx (hunk 1 above)
Comment (christopherhuii) [reply src/components/Form/Location/Address.jsx]: good catch, removed

**Comment by christopherhuii** [comment]
> Also out of curiosity, which aspect of this resolved #1365?

Based on the console error, I was able to determine that something in the Accordion was rendering an object, which isn't allowed. After a lot of debugging, I was able to find out that the error was coming from within `src/components/Summary/Summary.jsx` because it was trying to render an object.

`this.props.left` is a country with a `null` value:
```
{
  value: null
}
```

The `countryString` function was returning the `null` object, which was causing problems in the rendering. So updating the `countryString` to account for `null` fixed it.
