### PR TITLE
Fix accordion ui bugs

### LINKED ISSUE #460: Spacing under close button on accordions
The line under the word "Close" should match the distance to the word as in the type under "person 1" in the example below. 

screen shot 2018-06-20 at 3 53 28 pm

**This occurs when** an accordion element it scrolled up and turns into a sticky header. 

**Browser**
Chrome
**System**
Mac

### LINKED ISSUE #712: Accordion title issues
**What did you do?**

Created two accordions for "Summary of foreign financial support" on the Foreign national support
in the Foreign Associations section

*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*
screen shot 2018-08-20 at 9 55 40 am

the accordion titles were generic "Support 1:Provide details of foreign financial support below"

There should be some title after "Support #:" that indicates what is in the accordion. I recommend that the information show the name of the person supported.

Browser / system

Chrome
Mac

### PR DESCRIPTION
**Pull request by line47**
Fixes #460 
Fixes #712 

screen shot 2018-10-16 at 11 55 27 am
screen shot 2018-10-16 at 11 56 37 am
screen shot 2018-10-16 at 12 09 51 pm

### CODE REVIEW

File: src/components/Section/Foreign/Business/Employment.jsx [hunk 1]
```diff
@@ -42,14 +42,15 @@ export default class Employment extends SubsectionElement {
   }
 
   summary(item, index) {
-    const obj = item || {}
-    const date = DateSummary(item.Date)
-    const job = `${(obj.Description || {}).value || ''}`.trim() || ''
+    const o = (item || {}).Item || {}
+    const date = DateSummary(o.Dates)
+    const name = NameSummary(o.Name)
+    const type = i18n.t('foreign.business.employment.collection.summary.item')
```
Comment (hursey013) [inline src/components/Section/Foreign/Business/Employment.jsx]: Should `type` be used in the object below?

Comment (line47) [reply src/components/Section/Foreign/Business/Employment.jsx]: Thanks for that `const type` was not needed for either of these updates 👍

**Comment by ryanhofdotgov** [comment]
@line47 If you haven't already verified these CSS changes in IE11, can you load up test case #&#xfeff;5 quick scan of these there? Thanks.

**Comment by line47** [comment]
@ryanhofdotgov I will be verifying in IE11 as soon as i can get my VirtualBox working 😢 
I upgraded to High Sierra and now can't reinstall without this error  https://github.com/docksal/docksal/issues/417

File: src/components/Section/Foreign/Activities/Support.jsx [hunk 2]
```diff
@@ -42,7 +42,8 @@ export default class Support extends SubsectionElement {
   }
 
   summary(item, index) {
-    const name = NameSummary((item || {}).Name)
+    const o = (item || {}).Item || {}
```
Comment (hursey013) [inline src/components/Section/Foreign/Activities/Support.jsx]: The final ` || {}` on this is not needed since it'll already get set to an empty object inside the parentheses.

File: src/components/Section/Foreign/Business/Employment.jsx [hunk 3]
```diff
@@ -42,14 +42,14 @@ export default class Employment extends SubsectionElement {
   }
 
   summary(item, index) {
-    const obj = item || {}
-    const date = DateSummary(item.Date)
-    const job = `${(obj.Description || {}).value || ''}`.trim() || ''
+    const o = (item || {}).Item || {}
```
Comment (hursey013) [inline src/components/Section/Foreign/Business/Employment.jsx]: No final `|| {}` needed here either

**Comment by hursey013** [comment]
Looks like there are still some issues with alignment and text-overflow:
screen shot 2018-10-23 at 1 52 52 pm

**Comment by line47** [comment]
I'm hoping to be able to test in IE next week and resolve this, If not it might be best turn this issue over to @christopherhuii or Josh Franklin (who is not in the repo anymore) to get over the finish line 🏁

File: src/components/Section/Foreign/Business/Employment.jsx [hunk 4]
```diff
@@ -42,14 +42,14 @@ export default class Employment extends SubsectionElement {
   }
 
   summary(item, index) {
-    const obj = item || {}
-    const date = DateSummary(item.Date)
-    const job = `${(obj.Description || {}).value || ''}`.trim() || ''
+    const o = (item || {}).Item
```
Comment (hursey013) [inline src/components/Section/Foreign/Business/Employment.jsx]: Based on the issue we resolved above in `Foreign/Activities/Support.jsx`, we may want to add the ` || {}` back in here just in case, thoughts?

Comment (line47) [reply src/components/Section/Foreign/Business/Employment.jsx]: Yeah that makes sense 👍

**Comment by ryanhofdotgov** [comment]
This is ready for re-review

**Comment by hursey013** [comment]
I'm going to need to go through the process of getting `VMware Fusion` before I can validate this one, my VIrtualbox install is longer working either 🙁

**Comment by line47** [comment]
someone from the Truss team could probably review @christopherhuii ?

**Comment by ryanhofdotgov** [comment]
@christopherhuii I've closed #460 since the line has been removed in another PR. If you're fine with the changes, I would go ahead and approve/merge/etc., then open up a follow-on issue to fix the alignment of the text. It is a minor issue and will allow Scott to wrap up his work on the project.
